id: sapor_ai_agent_health_summary
namespace: sapor.ai

description: |
  Kestra AI Agent workflow that:
  1. Summarizes data from multiple SAPOR systems
  2. Makes intelligent decisions based on the summary
  3. Automates health monitoring and recommendations

labels:
  project: SAPOR
  type: ai-agent
  purpose: health-monitoring

inputs:
  - id: analysis_depth
    type: STRING
    defaults: comprehensive
    description: Level of analysis (quick, standard, comprehensive)

tasks:
  # Step 1: Gather data from MongoDB
  - id: fetch_meal_data
    type: io.kestra.plugin.mongodb.Find
    connection:
      uri: "{{ secret('MONGODB_URI') }}"
    database: sapor
    collection: meals
    filter: |
      {
        "createdAt": {
          "$gte": { "$date": "{{ now() | dateAdd(-7, 'DAYS') }}" }
        }
      }
    fetchType: FETCH_ALL

  - id: fetch_user_feedback
    type: io.kestra.plugin.mongodb.Find
    connection:
      uri: "{{ secret('MONGODB_URI') }}"
    database: sapor
    collection: feedbacks
    filter: |
      {
        "createdAt": {
          "$gte": { "$date": "{{ now() | dateAdd(-7, 'DAYS') }}" }
        }
      }
    fetchType: FETCH_ALL

  # Step 2: Fetch Recipe Analysis Results
  - id: fetch_recipe_analysis
    type: io.kestra.plugin.core.http.Request
    uri: http://backend:3001/api/recipes/batch-analyze
    method: POST
    contentType: application/json
    body: |
      {
        "recipes": {{ outputs.fetch_meal_data.rows | jq('.[] | {name, calories, sodium, sugar}') }}
      }

  # Step 3: Fetch Codebase Health
  - id: fetch_codebase_health
    type: io.kestra.plugin.core.http.Request
    uri: http://backend:3001/api/codebase/scan
    method: POST
    contentType: application/json
    body: |
      {
        "options": {
          "maxFiles": 50,
          "useAI": false
        }
      }

  # Step 4: AI Agent - Summarize All Data
  - id: ai_agent_summarize
    type: io.kestra.plugin.openai.ChatCompletion
    apiKey: "{{ secret('OPENAI_API_KEY') }}"
    model: gpt-4-turbo-preview
    messages:
      - role: system
        content: |
          You are the SAPOR Health Intelligence AI Agent. Your role is to:
          1. Analyze data from multiple systems (meals, user feedback, recipe analysis, codebase health)
          2. Identify patterns, trends, and anomalies
          3. Provide actionable insights and recommendations
          4. Make data-driven decisions for system improvements
          
          Provide your analysis in structured JSON format with:
          - summary: Overall health summary
          - metrics: Key performance indicators
          - insights: Important findings
          - recommendations: Actionable suggestions
          - decisions: Automated decisions to make
          - priority: Priority level (low, medium, high, critical)
      
      - role: user
        content: |
          Analyze the following SAPOR system data and provide comprehensive insights:
          
          ## Meal Data (Last 7 Days)
          Total Meals: {{ outputs.fetch_meal_data.rows | length }}
          Meals: {{ outputs.fetch_meal_data.rows | tojson }}
          
          ## User Feedback (Last 7 Days)
          Total Feedback: {{ outputs.fetch_user_feedback.rows | length }}
          Feedback: {{ outputs.fetch_user_feedback.rows | tojson }}
          
          ## Recipe Health Analysis
          {{ outputs.fetch_recipe_analysis.body | tojson }}
          
          ## Codebase Health
          {{ outputs.fetch_codebase_health.body | tojson }}
          
          Provide your analysis considering:
          1. Recipe health trends (are recipes getting healthier?)
          2. User satisfaction (feedback patterns)
          3. System reliability (codebase health)
          4. Performance metrics
          5. Areas requiring immediate attention

  # Step 5: Parse AI Agent Response
  - id: parse_ai_insights
    type: io.kestra.plugin.core.flow.Switch
    value: "{{ outputs.ai_agent_summarize.choices[0].message.content }}"
    cases:
      # Try to parse as JSON
      default:
        - id: extract_insights
          type: io.kestra.plugin.scripts.python.Script
          docker:
            image: python:3.11-slim
          script: |
            import json
            import sys
            
            # Parse AI response
            ai_response = """{{ outputs.ai_agent_summarize.choices[0].message.content }}"""
            
            try:
                # Try to extract JSON from response
                if "```json" in ai_response:
                    json_start = ai_response.find("```json") + 7
                    json_end = ai_response.find("```", json_start)
                    json_str = ai_response[json_start:json_end].strip()
                else:
                    json_str = ai_response
                
                insights = json.loads(json_str)
                
                # Output structured data
                print(json.dumps({
                    "summary": insights.get("summary", ""),
                    "priority": insights.get("priority", "medium"),
                    "metrics": insights.get("metrics", {}),
                    "insights": insights.get("insights", []),
                    "recommendations": insights.get("recommendations", []),
                    "decisions": insights.get("decisions", [])
                }))
                
            except Exception as e:
                # Fallback if JSON parsing fails
                print(json.dumps({
                    "summary": ai_response[:500],
                    "priority": "medium",
                    "error": str(e)
                }))

  # Step 6: AI Agent Decision Making
  - id: ai_agent_decide
    type: io.kestra.plugin.core.flow.Switch
    value: "{{ outputs.extract_insights.vars.priority }}"
    cases:
      critical:
        - id: critical_alert
          type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
          url: "{{ secret('SLACK_WEBHOOK_URL') }}"
          payload: |
            {
              "text": "🚨 CRITICAL: SAPOR Health Alert",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚨 Critical Health Issue Detected"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Summary:*\n{{ outputs.extract_insights.vars.summary }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Immediate Actions Required:*\n{{ outputs.extract_insights.vars.decisions | join('\n') }}"
                  }
                }
              ]
            }
        
        - id: trigger_emergency_scan
          type: io.kestra.plugin.core.http.Request
          uri: http://backend:3001/api/codebase/scan
          method: POST
          body: |
            {
              "options": {
                "maxFiles": 100,
                "useAI": true
              }
            }
      
      high:
        - id: high_priority_notification
          type: io.kestra.plugin.core.log.Log
          message: |
            ⚠️ HIGH PRIORITY: {{ outputs.extract_insights.vars.summary }}
            Recommendations: {{ outputs.extract_insights.vars.recommendations }}
        
        - id: schedule_deep_analysis
          type: io.kestra.plugin.core.trigger.Schedule
          cron: "0 */6 * * *"  # Every 6 hours
      
      medium:
        - id: standard_monitoring
          type: io.kestra.plugin.core.log.Log
          message: |
            ℹ️ STANDARD: SAPOR health is normal
            Summary: {{ outputs.extract_insights.vars.summary }}
      
      low:
        - id: routine_report
          type: io.kestra.plugin.core.log.Log
          message: "✅ All systems healthy"

  # Step 7: Store AI Insights in MongoDB
  - id: store_ai_insights
    type: io.kestra.plugin.mongodb.InsertOne
    connection:
      uri: "{{ secret('MONGODB_URI') }}"
    database: sapor
    collection: ai_insights
    document: |
      {
        "timestamp": "{{ now() }}",
        "type": "health_summary",
        "priority": "{{ outputs.extract_insights.vars.priority }}",
        "summary": "{{ outputs.extract_insights.vars.summary }}",
        "metrics": {{ outputs.extract_insights.vars.metrics | tojson }},
        "insights": {{ outputs.extract_insights.vars.insights | tojson }},
        "recommendations": {{ outputs.extract_insights.vars.recommendations | tojson }},
        "decisions": {{ outputs.extract_insights.vars.decisions | tojson }},
        "data_sources": {
          "meals_analyzed": {{ outputs.fetch_meal_data.rows | length }},
          "feedback_count": {{ outputs.fetch_user_feedback.rows | length }},
          "codebase_health": {{ outputs.fetch_codebase_health.body.debtReport.healthScore }}
        }
      }

  # Step 8: Generate Visual Report
  - id: generate_report
    type: io.kestra.plugin.scripts.python.Script
    docker:
      image: python:3.11-slim
    beforeCommands:
      - pip install matplotlib pandas
    script: |
      import json
      import matplotlib.pyplot as plt
      import pandas as pd
      from datetime import datetime
      
      # Parse insights
      insights = json.loads("""{{ outputs.extract_insights.output }}""")
      
      # Create health dashboard
      fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(15, 10))
      fig.suptitle('SAPOR AI Health Dashboard', fontsize=16, fontweight='bold')
      
      # Metrics visualization
      metrics = insights.get('metrics', {})
      if metrics:
          ax1.bar(metrics.keys(), metrics.values())
          ax1.set_title('Key Metrics')
          ax1.set_ylabel('Value')
      
      # Priority indicator
      priority_colors = {'low': 'green', 'medium': 'yellow', 'high': 'orange', 'critical': 'red'}
      priority = insights.get('priority', 'medium')
      ax2.pie([1], labels=[f"Priority: {priority.upper()}"], 
              colors=[priority_colors.get(priority, 'gray')],
              autopct='%1.0f%%', startangle=90)
      
      # Recommendations count
      recs = insights.get('recommendations', [])
      ax3.barh(['Recommendations'], [len(recs)], color='blue')
      ax3.set_title('Action Items')
      
      # System health
      health_data = {
          'Meals': {{ outputs.fetch_meal_data.rows | length }},
          'Feedback': {{ outputs.fetch_user_feedback.rows | length }},
          'Code Health': {{ outputs.fetch_codebase_health.body.debtReport.healthScore }}
      }
      ax4.bar(health_data.keys(), health_data.values(), color=['green', 'blue', 'purple'])
      ax4.set_title('System Overview')
      
      plt.tight_layout()
      plt.savefig('{{ outputDir }}/health_report.png', dpi=300, bbox_inches='tight')
      print("Report generated successfully")

triggers:
  - id: daily_health_check
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 * * *"  # Every day at 9 AM

  - id: on_critical_feedback
    type: io.kestra.plugin.mongodb.Trigger
    connection:
      uri: "{{ secret('MONGODB_URI') }}"
    database: sapor
    collection: feedbacks
    filter: |
      {
        "rating": { "$lte": 2 }
      }
